---
- name: Ensure subscription-manager package is installed
  yum:
    name: subscription-manager
    state: present

- name: Register and subscribe to multiple pool IDs.
  redhat_subscription:
    state: present
    force_register: "{{ ovirt_repositories_force_register }}"
    username: "{{ ovirt_repositories_rh_username | mandatory }}"
    password: "{{ ovirt_repositories_rh_password | mandatory }}"
    pool_ids: "{{ ovirt_repositories_pool_ids }}"
  when:  ovirt_repositories_pool_ids is defined

- name: Use default subscription pool name for Red Hat Virtualization.
  redhat_subscription:
    state: present
    force_register: "{{ ovirt_repositories_force_register }}"
    username: "{{ ovirt_repositories_rh_username | mandatory }}"
    password: "{{ ovirt_repositories_rh_password | mandatory }}"
    pool: '^Red Hat Virtualization$'
  when:  ovirt_repositories_pool_ids is not defined

- name: Include target/version specific variables.
  include_vars: "{{ ovirt_repositories_target_host }}_{{ ovirt_repositories_ovirt_version }}.yml"

- name: Enable required repositories.
  command: "subscription-manager repos --enable={{ item }}"
  with_items: "{{ ovirt_repositories_subscription_manager_repos }}"
